apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: banking
  source:
    repoURL: https://github.com/zoumana001/GITOPS_PROJECT_BANKING.git
    targetRevision: main
    path: banking-project/banking-microservices/helm-charts/platforms-tools/cert-manager
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
