server:
  port: 8081

spring:
  application:
    name: transaction-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true